name: Release CI

on:
  pull_request:
    branches: [ 'release/**' ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18'
      # Run tests
      - name: Run unit tests
        run: |
          npm ci
          npm run test:unit
      # merge after successful build and test
      # - name: Merge branch to main
      #  uses: devmasx/merge-branch@master
      #  with:
      #    type: now
      #    from_branch: release
      #    target_branch: main
      #    github_token: ${{ github.token }}

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18'

      # Runs a single command using the runners shell
      - name: Install, Build, Publish
        run: |
          npm ci
          npm run build
          echo Publish to NPM

      # Publish to npm
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
